"""Tambah password hash ke tabel mahasiswa

Revision ID: bef9ef838bf7
Revises: 
Create Date: 2025-06-08 15:35:03.241250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef9ef838bf7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dosen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_dosen', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_dosen')
    )
    op.create_table('mahasiswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_mahasiswa', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_mahasiswa')
    )
    op.create_table('matakuliah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_mk', sa.String(length=20), nullable=False),
    sa.Column('nama_mk', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jadwal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mk_id', sa.Integer(), nullable=False),
    sa.Column('dosen_id', sa.Integer(), nullable=False),
    sa.Column('hari', sa.String(length=20), nullable=False),
    sa.Column('jam_mulai', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['dosen_id'], ['dosen.id'], ),
    sa.ForeignKeyConstraint(['mk_id'], ['matakuliah.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sesi_perkuliahan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jadwal_id', sa.Integer(), nullable=False),
    sa.Column('dosen_pengajar_id', sa.Integer(), nullable=False),
    sa.Column('pertemuan_ke', sa.Integer(), nullable=True),
    sa.Column('waktu_mulai', sa.DateTime(), nullable=True),
    sa.Column('waktu_selesai', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dosen_pengajar_id'], ['dosen.id'], ),
    sa.ForeignKeyConstraint(['jadwal_id'], ['jadwal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_absensi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesi_id', sa.Integer(), nullable=False),
    sa.Column('mahasiswa_id', sa.Integer(), nullable=False),
    sa.Column('waktu_absen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mahasiswa_id'], ['mahasiswa.id'], ),
    sa.ForeignKeyConstraint(['sesi_id'], ['sesi_perkuliahan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_absensi')
    op.drop_table('sesi_perkuliahan')
    op.drop_table('jadwal')
    op.drop_table('matakuliah')
    op.drop_table('mahasiswa')
    op.drop_table('dosen')
    # ### end Alembic commands ###
